spring:
  # Templates reloading during development
  thymeleaf:
    prefix: classpath:/templates/
    cache: false

  # Static resources reloading during development
  resources:
    static-locations: file:src/main/resources/static/
    cache-period: 0